config/routes.rb
Rails.application.routes.draw do
  root to: "canvasses#new"

  resources :candidates
  resources :priorities
  resources :canvasses do
    resources :votes
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/canvasses_controller.rb
class CanvassesController < ApplicationController
  before_action :set_canvass, only: [:show, :edit, :update, :destroy]

  # GET /canvasses
  # GET /canvasses.json
  def index
    @canvasses = Canvass.all
  end

  # GET /canvasses/1
  # GET /canvasses/1.json
  def show
  end

  # GET /canvasses/new
  def new
    @canvass = Canvass.new
  end

  # GET /canvasses/1/edit
  def edit
  end

  # POST /canvasses
  # POST /canvasses.json
  def create
    @canvass = Canvass.new(canvass_params)

    respond_to do |format|
      if @canvass.save
        format.html { redirect_to @canvass, notice: 'Canvass was successfully created.' }
        format.json { render :show, status: :created, location: @canvass }
      else
        format.html { render :new }
        format.json { render json: @canvass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /canvasses/1
  # PATCH/PUT /canvasses/1.json
  def update
    respond_to do |format|
      if @canvass.update(canvass_params)
        format.html { redirect_to @canvass, notice: 'Canvass was successfully updated.' }
        format.json { render :show, status: :ok, location: @canvass }
      else
        format.html { render :edit }
        format.json { render json: @canvass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canvasses/1
  # DELETE /canvasses/1.json
  def destroy
    @canvass.destroy
    respond_to do |format|
      format.html { redirect_to canvasses_url, notice: 'Canvass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_canvass
      @canvass = Canvass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canvass_params
      params.require(:canvass).permit(:question)
    end
end

app/helpers/canvasses_helper.rb
module CanvassesHelper
end

app/views/canvasses/_form.html.erb
<%= form_with(model: canvass, local: true) do |form| %>
  <% if canvass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(canvass.errors.count, "error") %> prohibited this canvass from being saved:</h2>

      <ul>
        <% canvass.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :question, placeholder: "What's your favorite flavor of ice cream?", size: 60 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/canvasses/edit.html.erb
<h1>I want to know...</h1>

<%= render 'form', canvass: @canvass %>

<%= link_to 'Show', @canvass %> |
<%= link_to 'Back', canvasses_path %>

app/views/canvasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Canvasses</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @canvasses.each do |canvass| %>
      <tr>
        <td><%= canvass.question %></td>
        <td><%= link_to 'Show', canvass %></td>
        <td><%= link_to 'Edit', edit_canvass_path(canvass) %></td>
        <td><%= link_to 'Destroy', canvass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Canvass', new_canvass_path %>

app/views/canvasses/new.html.erb
<h1>I want to know...</h1>

<%= render 'form', canvass: @canvass %>

<% if(Rails.env.development?) %>
<h3>Recent polls:</h3>
  <ul>
    <% Canvass.order(created_at: :desc).limit(5).each do |canvass| %>
      <li><%= link_to(canvass.question, canvass) %></li>
    <% end %>
  </ul>
<% end %>

app/views/canvasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @canvass.question %>
</p>

<%= render 'votes/form', vote: @canvass.votes.build %>

<h3>Recent votes:</h3>
<ul>
  <% @canvass.votes.order(created_at: :desc).each do |vote| %>
    <li>
      <%= link_to(vote.candidate.name, [vote.canvass, vote]) %>
      because I care about <%= vote.priority_1 %>, <%= vote.priority_2 %>, and <%= vote.priority_3 %>.
      And also because <%= vote.comment %>.
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_canvass_path(@canvass) %> |
<%= link_to 'Back', canvasses_path %>