config/routes.rb
Rails.application.routes.draw do
  root to: "canvasses#new"

  resources :candidates
  resources :priorities
  resources :canvasses do
    resources :votes
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  before_action :set_quality, only: [:show, :edit, :update, :destroy]

  # GET /qualities
  # GET /qualities.json
  def index
    @priorities = Priority.all
  end

  # GET /qualities/1
  # GET /qualities/1.json
  def show
  end

  # GET /qualities/new
  def new
    @priority = Priority.new
  end

  # GET /qualities/1/edit
  def edit
  end

  # POST /qualities
  # POST /qualities.json
  def create
    @priority = Priority.new(quality_params)

    respond_to do |format|
      if @priority.save
        format.html { redirect_to @priority, notice: 'Quality was successfully created.' }
        format.json { render :show, status: :created, location: @priority }
      else
        format.html { render :new }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualities/1
  # PATCH/PUT /qualities/1.json
  def update
    respond_to do |format|
      if @priority.update(quality_params)
        format.html { redirect_to @priority, notice: 'Quality was successfully updated.' }
        format.json { render :show, status: :ok, location: @priority }
      else
        format.html { render :edit }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualities/1
  # DELETE /qualities/1.json
  def destroy
    @priority.destroy
    respond_to do |format|
      format.html { redirect_to priorities_url, notice: 'Quality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quality
      @priority = Priority.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quality_params
      params.require(:priority).permit(:tag)
    end
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/views/priorities/_form.html.erb
<%= form_with(model: quality, local: true) do |form| %>
  <% if quality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quality.errors.count, "error") %> prohibited this quality from being saved:</h2>

      <ul>
        <% quality.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/priorities/edit.html.erb
<h1>Editing Quality</h1>

<%= render 'form', quality: @priority %>

<%= link_to 'Show', @priority %> |
<%= link_to 'Back', priorities_path %>

app/views/priorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qualities</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @priorities.each do |quality| %>
      <tr>
        <td><%= quality.tag %></td>
        <td><%= link_to 'Show', quality %></td>
        <td><%= link_to 'Edit', edit_priority_path(quality) %></td>
        <td><%= link_to 'Destroy', quality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quality', new_priority_path %>

app/views/priorities/new.html.erb
<h1>New Quality</h1>

<%= render 'form', quality: @priority %>

<%= link_to 'Back', priorities_path %>

app/views/priorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @priority.tag %>
</p>

<%= link_to 'Edit', edit_priority_path(@priority) %> |
<%= link_to 'Back', priorities_path %>