config/routes.rb
Rails.application.routes.draw do
  root to: "canvasses#new"

  resources :candidates
  resources :priorities
  resources :canvasses do
    resources :votes
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  attr_accessor :candidate_name, :priority_1, :priority_2, :priority_3
  belongs_to :candidate
  belongs_to :canvass
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @canvass = Canvass.find_by!(id: params.fetch(:canvass_id))
    @candidate = @canvass.candidates.find_or_create_by!(name: params.dig("vote", "candidate_name"))
    @vote = @canvass.votes.build(candidate: @candidate)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to [@canvass, @vote], notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
        params.require(:vote).permit(:candidate_id, :candidate_name, :primary_quality_id, :secondary_quality_id, :tertiary_quality_id, :comment, :priority_1, :priority_2, :priority_3)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<% canvass = vote.canvass or fail "Must supply a valid canvass" %>
<%= form_with(model: [canvass, vote], local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
        <% vote.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    I prefer
    <%= form.text_field :candidate_name, placeholder: "Butter pecan" %>
    because I care about
    <%= form.text_field :priority_1, placeholder: "butteriness" %>
    and
    <%= form.text_field :priority_2, placeholder: "chunkiness" %>
    and
    <%= form.text_field :priority_3, placeholder: "nuttiness" %>
  </div>

  <div class="field">
    <%= form.label :comment, class: "inline" %>
    <%= form.text_field :comment, placeholder: "it just tastes good" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Candidate</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.candidate_id %></td>
        <td><%= vote.comment %></td>
        <td><%= link_to 'Show', [vote.canvass, vote] %></td>
        <td><%= link_to 'Edit', edit_canvass_vote_path(vote.canvass, vote) %></td>
        <td><%= link_to 'Destroy', [vote.canvass, vote], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_canvass_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', canvass_votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Candidate:</strong>
  <%= @vote.candidate_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @vote.comment %>
</p>

<%= link_to 'Edit', edit_canvass_vote_path %> |
<%= link_to 'Back', canvass_votes_path %>